Add new directory structure lel makefile

diff --git a/migrated/migrated/move_me/bsp-packages/Makefile b/migrated/migrated/move_me/bsp-packages/Makefile
--- a/migrated/migrated/move_me/bsp-packages/Makefile
+++ b/migrated/migrated/move_me/bsp-packages/Makefile
@@ -20,12 +20,40 @@
 
 # Do not recurse the following subdirs
 MAKE_FILTERS  = Makefile README.md .
+CATEGORIES    = laptop desktop set-top-box single-board-computer
 
 # ------------------------------------------------------------------------------
 #
 # Targets not associated with a file (aka PHONY)
 #
 .PHONY: help
+
+#check que tes subdirs de category ont la et ont un lien makefile valide ensuite ca recurse
+check :
+	@echo "te faut l include de la liste des error codes et la fonction dft-error" ;
+	@echo "te faut recuprer le bout de code qui fait le readlink dans une var" ;
+	# Board level directory must contain board.mk file, kernel folder and u-boot folder
+	# Mandatory folders content check (otherwise recusive targets may not work)
+	@for i in $(CATEGORIES) ; do \
+		if [ ! -d $$i ] ; then \
+		echo "Warning : $$i category folder is missing, recursive targets may fail or produce incomplete set of binaries." ; \
+		fi ; \
+		if [ ! -e "$$i/Makefile" ] ; then \
+			echo "Makefile in $(shell pwd)/$$i is Missing. It should be a symlink to  ../../buildsystem/shared/u-boot-board.makefile" ; \
+			echo "You can fix with the following shell commands :" ; \
+			echo "ln -s ../../buildsystem/shared/category.makefile $$i/Makefile" ; \
+			echo "git add $$i/Makefile" ; \
+			echo "exit 101101" ; \
+			exit 1 ; \
+		fi ; \
+		if [ ! $(shell readlink $$i/Makefile) = "../../buildsystem/shared/u-boot-board.makefile" ] ; then \
+			echo "iTODOMakefile symlink in $(shell pwd)/$$i must link to ../../buildsystem/shared/u-boot-board.makefile" ; \
+			echo "It targets to $(shell readlink $i/Makefile)" ; \
+			echo "exit 825" ; \
+			exit 1 ; \
+		fi ; \
+	done ; \
+
 
 # Catch all target. Call the same targets in each subfolder
 %:
